#!/bin/bash

set -euo pipefail

PACKAGES="grim slurp jg hyprctl"
FOLDER=$HOME/.local/share/Screenshots
ACTIVE=$(hyprctl activewindow -j | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')
MODE="$1"

# Check for require packages
if ! command -v $PACKAGES >/dev/null 2>&1; then
    exit 1
fi

# Check if default folder exists
if [[ !  -d $FOLDER ]]; then
	mkdir -p $FOLDER
fi

# MODES
area () {
	grim -g "$(slurp)" "$FOLDER/Screenshot-$(date +%F_%H-%M-%S).png"
}

active () {
	grim -g "$ACTIVE" $FOLDER/Screenshot$(date +%F_%H-%M-%S).png
}

dual () {
	grim "$FOLDER/Screenshot-$(date +%F_%H-%M-%S).png"
}

case "$MODE" in
	AREA)
		area
		;;
	ACTIVE)
		active
		;;
	DUAL)
		dual
		;;
esac
