#!/bin/bash

set -euo pipefail

PACKAGES="grim slurp jg hyprctl"
FOLDER=$HOME/.local/share/Screenshots

# Check for require packages
if ! command -v $PACKAGES >/dev/null 2>&1; then
    exit 1
fi

# Check if default folder exists
if [[ !  -d $FOLDER ]]; then
	mkdir -p $FOLDER
fi

# Options
usage() {
	local prog=${0##*/}
	cat <<-EOF
	Usage: $prog [options]

	Options:
	  -h    print this message and exit
	  -a    capture the selected area
	  -c    capture the active monitor
	  -d    capture both monitors
	EOF
}

area() {
	grim -g "$(slurp)" "$FOLDER/Screenshot-$(date +%F_%H-%M-%S).png"
}

active() {
	local ACTIVE=$(hyprctl activewindow -j | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')
	grim -g "$ACTIVE" $FOLDER/Screenshot$(date +%F_%H-%M-%S).png
}

dual() {
	grim "$FOLDER/Screenshot-$(date +%F_%H-%M-%S).png"
}

main() {
	local opt OPTIND OPTARG
	while getopts 'hacd' opt; do
		case "$opt" in
			h) usage; return 0;;
			a) area; return 0;;
			c) active; return 0;;
			d) dual; return 0;;
			*) usage >&2; return 1;;
		esac
	done
	shift "$((OPTIND - 1))"

	if (($# == 0)); then
		usage >&2
		return 1
	fi

	"$@"
}

main "$@"
