#!/bin/bash

set -euo pipefail

PACKAGES='umu-run ge-proton'
WINEPREFIX_DIR="$HOME/Plus/Games/umu-launcher"
PROTON_DIR="/usr/share/steam/compatibilitytools.d/ge-proton"
OPTION="$1"
GAME_PATH="$2"

# Check for required packages
if ! command -v $PACKAGES >/dev/null 2>&1; then
    exit 1
fi

Xwayland () {
    WINEPREFIX="$WINEPREFIX_DIR" \
    PROTONPATH="$PROTON_DIR" \
    umu-run "$GAME_PATH"
}

Wayland () {
    PROTON_USE_WOW64=1 \
    PROTON_ENABLE_WAYLAND=1 \
    PROTONFIXES_DISABLE=1 \
    MANGOHUD=1 \
    WINEPREFIX="$WINEPREFIX_DIR" \
    PROTONPATH="$PROTON_DIR" \
    umu-run "$GAME_PATH"
}

case "$OPTION" in
	XWAYLAND)
		Xwayland
		;;
	WAYLAND)
		Wayland
		;;
esac
