#!/bin/bash

#############
# Fastfetch #
#############
fastfetch

##########
# Promit #
##########
PS1='\[\033[1;32m\]\u \[\033[0;37m\]\W \[\033[1;32m\]>\[\033[0;37m\] '

##########
# Locale #
##########
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

###########
# Editors #
###########
export EDITOR=micro
export VISUAL=$EDITOR

###############
# Preferences #
###############
shopt -s autocd
shopt -s checkwinsize
shopt -s nullglob

########################
# XDG Base Directories #
########################
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"

export HISTFILE="$XDG_STATE_HOME"/bash/history
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc
export WINEPREFIX="$XDG_DATA_HOME"/wine
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java

###########
# Aliases #
###########

# General
alias ..='cd ..'
alias ..2='cd ../../'
alias ..3='cd ../../../'
alias ..4='cd ../../../../'
alias ..5='cd ../../../../../'
alias ls='ls -Ahl --color=auto'
alias grep='grep --color=auto'
alias update-grub='sudo grub2-mkconfig -o /boot/grub2/grub.cfg'

# DNF
alias i='sudo dnf install'
alias r='sudo dnf remove'
alias u='sudo dnf update --refresh'
alias s='dnf search'
alias ar='sudo dnf autoremove'

# GIT
alias gc='git clone'
alias gi='git init'
alias ga='git add'
alias gmv='git mv'
alias gre='git restore'
alias grm='git rm'
alias gco='git commit'
alias gpr='git pull --rebase origin main'
alias gp='git push'

# Colors
NOCOLOR='\033[0m'
BLACK='\033[30m'
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
BLUE='\033[34m'
MAGENTA='\033[35m'
CYAN='\033[36m'
WHITE='\033[1;37m'
